# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef23185581da98cf2243867d465215f8"
application_url = "https://authorization-tricks-sender-fountain.trycloudflare.com"
embedded = true
name = "Minga Routines"
handle = "minga-routines"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-routine.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "orders/create" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_orders"

[auth]
redirect_urls = [
  "https://authorization-tricks-sender-fountain.trycloudflare.com/auth/callback",
  "https://authorization-tricks-sender-fountain.trycloudflare.com/auth/shopify/callback",
  "https://authorization-tricks-sender-fountain.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://authorization-tricks-sender-fountain.trycloudflare.com"
subpath = "routine"
prefix = "apps"

[pos]
embedded = false
