# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef23185581da98cf2243867d465215f8"
name = "Minga Routines"
handle = "minga-routines"
application_url = "https://routine-app-xgu1.onrender.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files"

[auth]
redirect_urls = [
  "https://routine-app-xgu1.onrender.com/auth/callback",
  "https://routine-app-xgu1.onrender.com/auth/shopify/callback",
  "https://routine-app-xgu1.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://routine-app-xgu1.onrender.com/webhooks"

[app_proxy]
url = "https://routine-app-xgu1.onrender.com/"
subpath = "routine"
prefix = "apps"

[pos]
embedded = false
