# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4dafbcbfcd37dcde3f18a13eb245dd16"
name = "routine-dev"
handle = "routine-dev"
application_url = "https://fcc-seeing-spend-baby.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-routine.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files"

[auth]
redirect_urls = [
  "https://fcc-seeing-spend-baby.trycloudflare.com/auth/callback",
  "https://fcc-seeing-spend-baby.trycloudflare.com/auth/shopify/callback",
  "https://fcc-seeing-spend-baby.trycloudflare.com/api/auth/callback",
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
