# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4dafbcbfcd37dcde3f18a13eb245dd16"
name = "routine-dev"
handle = "routine-dev"
application_url = "https://a04f-49-37-67-143.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-routine.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files"

[auth]
redirect_urls = [
  "https://a04f-49-37-67-143.ngrok-free.app/auth/callback",
  "https://a04f-49-37-67-143.ngrok-free.app/auth/shopify/callback",
  "https://a04f-49-37-67-143.ngrok-free.app/api/auth/callback",
]

[webhooks]
api_version = "2024-10"

[app_proxy]
url = "https://a04f-49-37-67-143.ngrok-free.app"
subpath = "routine"
prefix = "apps"

[pos]
embedded = false
