# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "168e6852f40d9946e74f0afcead0e796"
name = "Routine Builder"
handle = "routine-builder"
application_url = "https://2c6c-2409-40e4-2052-d68b-eea8-260d-ae33-9062.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-03878ee5.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files"

[auth]
redirect_urls = [
  "https://2c6c-2409-40e4-2052-d68b-eea8-260d-ae33-9062.ngrok-free.app/auth/callback",
  "https://2c6c-2409-40e4-2052-d68b-eea8-260d-ae33-9062.ngrok-free.app/auth/shopify/callback",
  "https://2c6c-2409-40e4-2052-d68b-eea8-260d-ae33-9062.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
