# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4dafbcbfcd37dcde3f18a13eb245dd16"
application_url = "https://5cc4-2405-201-c018-78a9-6d0-7d6-6240-e0c3.ngrok-free.app"
embedded = true
name = "minga-routines-dev"
handle = "routine-dev"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "https://5cc4-2405-201-c018-78a9-6d0-7d6-6240-e0c3.ngrok-free.app/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files"

[auth]
redirect_urls = [
  "https://5cc4-2405-201-c018-78a9-6d0-7d6-6240-e0c3.ngrok-free.app/auth/callback",
  "https://5cc4-2405-201-c018-78a9-6d0-7d6-6240-e0c3.ngrok-free.app/auth/shopify/callback",
  "https://5cc4-2405-201-c018-78a9-6d0-7d6-6240-e0c3.ngrok-free.app/api/auth/callback"
]

[app_proxy]
url = "https://5cc4-2405-201-c018-78a9-6d0-7d6-6240-e0c3.ngrok-free.app"
subpath = "routine"
prefix = "apps"

[pos]
embedded = false

[build]
dev_store_url = "test-store-routine.myshopify.com"
automatically_update_urls_on_dev = true
