# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef23185581da98cf2243867d465215f8"
name = "Routine"
handle = "routine"
application_url = "https://routine-app-lilac.vercel.app"
embedded = true

[build]
dev_store_url = "test-store-routine.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files"

[auth]
redirect_urls = [
  "https://routine-app-lilac.vercel.app/auth/callback",
  "https://routine-app-lilac.vercel.app/auth/shopify/callback",
  "https://routine-app-lilac.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
