# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9388a5774685dae18ad95269e9767d2a"
name = "first-app"
handle = "first-app-1303"
application_url = "https://returning-jones-simultaneously-applied.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-03878ee5.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [
  "https://returning-jones-simultaneously-applied.trycloudflare.com/auth/callback",
  "https://returning-jones-simultaneously-applied.trycloudflare.com/auth/shopify/callback",
  "https://returning-jones-simultaneously-applied.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[app_proxy]
url = "https://returning-jones-simultaneously-applied.trycloudflare.com/app"
subpath = "amrutam-routine"
prefix = "apps"

[pos]
embedded = false
